 name: Backend CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x tec/gradlew

      - name: Build with Gradle (Without Tests)
        run: cd tec && ./gradlew clean build -x test

      - name: Run Tests
        run: cd tec && ./gradlew test

      - name: Upload Backend Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: tec/build/libs/*.jar
